name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c release -o /app --no-restore

    - name: DotnetVersionFinder
      id: project-version
      uses: AjdinHusic/DotnetVersionFinder@afe8f8e095ffebc9bf6e4785e0644904e491dcba
      with:
        path: CreatorCompanionPatcher/CreatorCompanionPatcher.csproj

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.1.0
      with: 
        path: ${{ GITHUB_WORKSPACE }}/app/

    - name: Github Release
      uses: 6thpath/action-github-release@ba2240e98166a319da08afddd79a2106215bf920
      with:
        tag_name: "v${{ steps.project-version.outputs.version }}"
        generate_release_notes: true
        files: |
          /app/CreatorCompanionPatcher.exe
          /app/CreatorCompanionPatcher.Installer.exe

    - name: Fetch Github Releases Data
      run: "wget https://api.github.com/repos/Misaka-L/CreatorCompanionPatcher/releases --output-document=releases-data"

    - name: Upload Patcher
      uses: zinh/ftp-uploader-action@10d256274547c8b84848edf454bfeb0b8a451c41
      with:
        ftpHostname: ${{ secrets.FtpHostName }}
        ftpUsername: ${{ secrets.FtpUsername }}
        ftpPassword: ${{ secrets.FtpPassword }}
        files: |
          ${{ GITHUB_WORKSPACE }}/app/CreatorCompanionPatcher.exe
          ${{ GITHUB_WORKSPACE }}/app/CreatorCompanionPatcher.Installer.exe
        dest: /app-publish

    - name: Upload Releases MetaData
      uses: zinh/ftp-uploader-action@10d256274547c8b84848edf454bfeb0b8a451c41
      with:
        ftpHostname: ${{ secrets.FtpHostName }}
        ftpUsername: ${{ secrets.FtpUsername }}
        ftpPassword: ${{ secrets.FtpPassword }}
        files: releases-data
        dest: /app-publish
