name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c release -o ${{ github.workspace }}/app --no-restore

    - name: DotnetVersionFinder
      id: project-version
      uses: chenryhabana205/dotnetgetversion@aab13340b6f5044b5b64f970a580c5946d4e8276
      with:
        VERSION_FILE_PATH: CreatorCompanionPatcher/CreatorCompanionPatcher.csproj

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.1.0
      with: 
        path: ${{ github.workspace }}/app/

    - name: Github Release
      uses: 6thpath/action-github-release@ba2240e98166a319da08afddd79a2106215bf920
      with:
        tag_name: "v${{ steps.project-version.outputs.TAG }}"
        generate_release_notes: true
        files: |
          ${{ github.workspace }}/app/CreatorCompanionPatcher.exe
          ${{ github.workspace }}/app/CreatorCompanionPatcher.Installer.exe

    - name: Fetch Github Releases Data
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir releases-data
        gh api repos/{owner}/{repo}/releases > releases-data/releases-data

    - name: Upload Patcher
      uses: koraykoska/s3-upload-github-action@c24afca3fabd71531a531cd105110175766aa9d9
      env:
        S3_ENDPOINT: ${{ secrets.S3EndPoint }}
        S3_BUCKET: ${{ secrets.S3Bucket }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3AccessKeyId }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3AccessKey }}
        FILE: ./app/

    - name: Upload Releases MetaData
      uses: koraykoska/s3-upload-github-action@c24afca3fabd71531a531cd105110175766aa9d9
      env:
        S3_ENDPOINT: ${{ secrets.S3EndPoint }}
        S3_BUCKET: ${{ secrets.S3Bucket }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3AccessKeyId }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3AccessKey }}
        FILE: ./releases-data/
